### ISSUE TITLE
cannot load image

### ISSUE THREAD

**Issue by NarenBabuR** [bennycheung/Food100_YOLO_Tools#1]
I have done all steps as you said. But I cant load the images. 
It throws me an error

**Comment by bennycheung** [comment]
Can you show me the error? one reminder, this set of tools is going with the post http://bennycheung.github.io/yolo-for-real-time-food-detection
It requires
(1) Food100 dataset has been downloaded
(2) food100_tk_label_bbox.py requires TKinter and PIL packages

**Comment by NarenBabuR** [comment]
Hello,

Thanks for reply...
My problem got solved...

By the way your implementation was interesting

**Comment by bennycheung** [comment]
Thanks, I am glad that your problem resolved. Enjoy!

**Comment by NarenBabuR** [comment]
Hai,

Can u please give me just an ML approach to solve the below problem

Scenario:
There is a surveillance camera in a class.

Problem :(Important)
Find the Machine Learning approach to find the malpractice in the class

We can't perform Supervised approach because we don't have enough data..

**Comment by bennycheung** [comment]
I see your problem is very interesting, to monitor malpractice in a classroom.

Unfortunately, with current deep learning technology, we need a large set of "label" data.
In your case, images that identify certain behaviour in class is labelled as "malpractice".
Also, with your problem, you are facing another challenge of bias data set, i.e. a lot of images of "normal" but only a few images of "malpractice".

I remembered in Kaggle. They have similar problem for "distracted driver detection":
https://www.kaggle.com/c/state-farm-distracted-driver-detection

You may want to study this case for inspirations.

**Comment by NarenBabuR** [comment]
Thank you very much :))
